version: "3.8"

volumes:
  pg_data: {}

services:
  postgres:
    image: postgres:$POSTGRES_VER
    container_name: pg
    volumes:
      - pg_data:/var/lib/postgresql/data
      - $PWD/db/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASS
    networks:
      - intranet

  oathkeeper:
    image: oryd/oathkeeper:$OATHKEEPER_VER
    container_name: oathkeeper
    depends_on:
      - kratos
    ports:
      - 8080:4455
      - 4456:4456
    command: serve proxy -c /etc/config/oathkeeper/oathkeeper.yml
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./oathkeeper:/etc/config/oathkeeper

  kratos-migrate:
    image: oryd/kratos:$KRATOS_VER
    container_name: krator-migrate
    links:
      - postgres:postgres
    environment:
      - DSN=$DSN_KRATOS
    networks:
      - intranet
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos:
    image: oryd/kratos:$KRATOS_VER
    container_name: kratos
    links:
      - postgres:postgres
    environment:
      - DSN=$DSN_KRATOS
    ports:
      - 4433:4433
      - 4434:4434
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:$KRATOS_UI_VER
    container_name: kratos-ui
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    networks:
      - intranet
    ports:
      - 4455:3000
    restart: on-failure

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    container_name: mailslurper
    ports:
      - 4436:4436
      - 4437:4437
    networks:
      - intranet

  keto-migrate:
    image: oryd/keto:$KETO_VER
    container_name: keto-migrate
    volumes:
      - type: bind
        source: ./keto
        target: /home/ory
    environment:
      - LOG_LEVEL=debug
      - DSN=$DSN_KETO
    command: [ migrate, up, -y ]
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - intranet

  keto-perms:
    image: oryd/keto:$KETO_VER
    container_name: keto-perms
    volumes:
      - type: bind
        source: ./keto
        target: /home/ory
    environment:
      - KETO_WRITE_REMOTE=keto:4467
      - KETO_READ_REMOTE=keto:4466
      - LOG_LEVEL=debug
      - DSN=$DSN_KETO
    depends_on:
      - postgres
    networks:
      - intranet

  keto:
    image: oryd/keto:$KETO_VER
    container_name: keto
    volumes:
      - type: bind
        source: ./keto
        target: /home/ory
    ports:
      - 4466:4466
      - 4467:4467
    depends_on:
      - keto-migrate
    environment:
      - DSN=$DSN_KETO
    networks:
      - intranet
    command: serve

  shorts:
    container_name: shorts
    build:
      context: .
    env_file: .env

    networks:
      - intranet

networks:
  intranet:
